version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: anime-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: animeDB
