services:
  mongo:
    image: mongo:6
    container_name: anime-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: animeDB

  backend:
    build: ./backend
    container_name: anime-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
